yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'Posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_post, name='group_list')
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='Main')),
    path('group/', include('posts.urls', namespace='Posts')),
    path('admin/', admin.site.urls),
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

# Create your models here.

User = get_user_model()


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='posts')
    group = models.ForeignKey('Group',
                              blank=True,
                              null=True,
                              on_delete=models.CASCADE)


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Group

# Create your views here.


def index(request):
    """Функция для выведения 10 последних записей."""

    posts = Post.objects.order_by('-pub_date')[:10]

    context = {
        'posts': posts
    }

    return render(request, 'posts/index.html', context)


def group_post(request, slug):
    """Функция для отображения сообщения для страницы группы."""

    group = get_object_or_404(Group, slug=slug)
    posts = Post.objects.filter(group=group).order_by('-pub_date')[:10]

    context = {
        'group': group,
        'posts': posts
    }
    return render(request, 'posts/group_list.html', context)

yatube/templates/base.html
  <!DOCTYPE html> <!-- Используется html 5 версии -->
  <html lang="ru"> <!-- Язык сайта - русский -->
    <head>
      {% load static %}
      <meta charset="utf-8"> <!-- Кодировка сайта -->
      <!-- Сайт готов работать с мобильными устройствами -->
       <meta name="viewport" content="width=device-width, initial-scale=1">
      <!-- Подключен файл со стандартными стилями бустрап -->
      <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
      <title> 
        {% block header %}
        {% endblock %}
      </title> 
    </head>
    <body>
      {% include 'includes/header.html' %}
      <main> 
        {% block content %}
        {% endblock %}
      </main>
      {% include 'includes/footer.html' %} 
    </body>
  </html>

yatube/templates/includes/footer.html
<class="border-top text-center py-3">
    <!-- тег span используется для добавления нужных стилей отдельным участкам текста --> 
    <p>© 2020 Copyright <span style="color:red">Ya</span>tube</p>

yatube/templates/includes/header.html
{% load static %}
    <nav class="navbar navbar-light" style="background-color: lightskyblue">
      <div class="container">
        <a class="navbar-brand" href="{% url 'Posts:index' %}">
          <img src="{% static 'img/logo.png' %}" width="30" height="30" class="alignleft" alt="">
          <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
          <span style="color:red">Ya</span>tube
        </a>
      </div>
    </nav>

yatube/templates/posts/group_list.html
<!-- templates/posts/group_list.html -->
{% extends 'base.html' %}
{% block content %}
  <title>Записи группы {{ group.title }}</title>
  <h1>{{ group.title }}</h1>
  <p>{{ group.description }}</p>
  {% for post in posts%}
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }}
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    <p>{{ post.text }}</p>
    <a href="">все записи группы</a>
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
{% endblock %}

yatube/templates/posts/index.html
<!-- templates/posts/index.html-->
{% extends 'base.html' %}
{% block content %}
  <title>Последние обновления на сайте</title>
  <h1>Последние обновления на сайте</h1>
  {% for post in posts %}
  <ul>
    <li>
      Автор: {{ post.author.get_full_name }}
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  <p>{{ post.text }}</p>
  {% if post.group %}
    <a href="{% url 'Posts:group_list' post.group.slug %}">все записи группы</a>
  {% endif %}
  {% if not forloop.last %}<hr>{% endif %}
  {% endfor %} 
{% endblock %}